esphome:
  name: smart_curtains
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password
    ap_timeout: 30s
  reboot_timeout: 0s

captive_portal:

ota:
   password: !secret ota_password

logger:

stepper:
  - platform: a4988
    id: curtains_stepper
    step_pin: 26
    dir_pin: 27
    max_speed: 1100 steps/s
    acceleration: inf
    deceleration: inf

api:
  password: !secret api_password
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: curtains_stepper
            target: !lambda 'return target;'
        - stepper.report_position:
            id: curtains_stepper
            position: 0
    - service: set_stepper_speed
      variables:
        target: int
      then:
        - stepper.set_speed:
            id: curtains_stepper
            speed: !lambda 'return target;'

switch:
  - platform: gpio
    internal: true
    id: left_stepper_switch
    pin: 25
    inverted: True
    restore_mode: ALWAYS_OFF
  - platform: gpio
    internal: true
    id: right_stepper_switch
    pin: 16
    inverted: True
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Stepper"
    lambda: |-
      return id(left_stepper_switch).state && id(right_stepper_switch).state;
    turn_on_action:
      - switch.turn_on: left_stepper_switch
      - switch.turn_on: right_stepper_switch
    turn_off_action:
      - switch.turn_off: left_stepper_switch
      - switch.turn_off: right_stepper_switch