# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
discovery:
  enable:
    - yeelight
    - xiaomi_gw
frontend:
  themes: !include_dir_merge_named themes

smartir:

mqtt:
  discovery: true
  broker: 192.168.1.128
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

timer:
  bathroom_light_timeout:
    duration: '00:20:00'

# Climate
binary_sensor:
  - platform: template
    sensors:
      ac_power_stub:
        friendly_name: "Air conditioner power stub"
        device_class: power
        value_template: "{{ On }}"
  - platform: mqtt
    name: 'Bath Motion sensor'
    state_topic: '/sensor/motion/bathroom/state'

climate:
  - platform: generic_thermostat
    name: Heat thermostat
    heater: switch.xiaomi_miio_switch
    target_sensor: sensor.climate_sensor_temperature
    target_temp: 21
  - platform: smartir
    name: Air conditioner
    unique_id: air_conditioner
    device_code: 1382
    controller_data: 192.168.1.50
    temperature_sensor: sensor.climate_sensor_temperature
    humidity_sensor: sensor.climate_sensor_humidity
    power_sensor: binary_sensor.ac_power_stub
# Home assistant
homeassistant:
  name: Smart Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Europe/Kiev
  elevation: 152
# Configure http to connect to google home
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Google home integration
google_assistant:
  project_id: smarthomehasssio
  expose_by_default: false
  entity_config:
    light.led_strip:
      expose: true
      room: kitchen
    climate.air_conditioner:
      expose: true
      room: bedroom
    light.room_lights:
      expose: true
      room: bedroom
    light.entrance_light:
      expose: true
      room: entrance
    light.yurii_room_lights:
      expose: false
      room: yurii bedroom
    cover.stepper_cover:
      expose: true
      room: bedroom
    switch.bathroom_switch:
      expose: true
      room: bathroom
light:
  - platform: group
    name: Room lights
    entities:
      - light.yeelight_color1_286c07b1c412
      - light.yeelight_color1_286c07b1c6ef
      - light.yeelight_color1_34ce008230a3
  - platform: group
    name: Yurii room lights
    entities:
        light.yeelight_ceiling3_7c49ebae06cf
  - platform: group
    name: Entrance light
    entities:
        light.yeelight_ceiling1_44237c883db8

tts:
  - platform: google_translate
switch:
  - platform: xiaomi_miio
    host: 192.168.1.178
    token: !secret miio_token
  - platform: broadlink
    host: 192.168.1.50
    mac: !secret broadlink_mac
    type: 'rm_mini'
input_select:
  input_mode:
    name: Input mode
    options:
      - CD mode
      - Optical mode
    initial: Optical mode
media_player:
  platform: universal
  name: Amplifier
  state_template: >
    on
  commands:
    volume_up:
      service: broadlink.send
      data:
        host: 192.168.1.50
        packet: JgAaAB0dHR0dHTsdHR0dHR4cHjk7HR4cHh0dAA0FAAAAAAAAAAAAAAAAAAA=
    volume_down:
      service: broadlink.send
      data:
        host: 192.168.1.50
        packet: JgAaAB0dHR0dHTsdHR0dHR4dHTo6Hh0dHToeAA0FAAAAAAAAAAAAAAAAAAA=
    volume_mute:
      service: broadlink.send
      data:
        host: 192.168.1.50
        packet: JgAYAB0dOjo7HR0dHhweHB4dHToeHDs6HgANBQ==
    select_source:
        service: input_select.select_option
        data_template:
          entity_id: input_select.input_mode
          option: '{{ source }}'
  attributes:
    is_volume_muted: false
    source: input_select.input_mode
    source_list: input_select.input_mode|options
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - !secret chat_ids
notify:
  - name: telegram_co2
    platform: telegram
    chat_id: !secret chat_ids
recorder:
  purge_keep_days: 3
  db_url: "sqlite://"
  exclude:
    domains:
      - updater
      - sun
      - persistent_notification
      - weather
      - binary_sensor
      - light
      - group
      - switch
      - automation
      - person
      - media_player
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
