esphome:
  name: "sonoff_kitchen_light"
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  reboot_timeout: 0min
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Sonoff kitchen light"
    password: "00000000"

captive_portal:

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
status_led:
  pin:
    number: GPIO13
    inverted: True
    
binary_sensor:
  - platform: gpio
    name: "[Kitchen] Light button"
    pin: GPIO04
    id: kitchen_light_button
    on_press:
      then:
        - switch.toggle:
            id: kitchen_light_switch

switch:
  - platform: gpio
    name: "[Kitchen] Light switch"
    pin: GPIO12
    id: kitchen_light_switch
    
sensor:
  - platform: wifi_signal
    name: "[Kitchen] WiFi signal"
    update_interval: 60s