esphome:
  name: co2_sensor_komnata_dlya_igr # Надо бы поменять
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "Wifi ssid" # Тут твой WiFi
  password: "here goes your pass"
  ap:
    ssid: "Wifi ssid to create" # Тут WiFi который будет включаться если твой отпадет
    password: "here goes your pass"
    ap_timeout: 30s
  reboot_timeout: 0s

captive_portal:

esp32_ble_tracker:

logger:

ota:

uart:
  rx_pin: 26
  tx_pin: 27
  baud_rate: 9600

sensor:
  - id: mhz19_sensor
    platform: mhz19
    co2:
      id: co2_sensor
      name: "CO2"
    update_interval: 20s
    automatic_baseline_calibration: false
  - platform: xiaomi_lywsd02
    id: xiaomi_climate_sensor
    mac_address: E7:2E:00:33:70:D7
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

light:
  - platform: rgb
    id: big_light
    name: "co2_light_big"
    red: output_red
    green: output_green
    blue: output_blue
  - platform: neopixelbus
    id: small_light
    pin: 23
    num_leds: 3
    name: "co2_light_small"

output:
  - platform: ledc
    pin: 16
    id: output_red
  - platform: ledc
    pin: 17
    id: output_green
  - platform: ledc
    pin: 18
    id: output_blue

interval:
  - interval: 10s
    then:
      - if:
          condition:
            lambda: 'return id(co2_sensor).state > 1500;'
          then:
            - light.turn_on:
                id: big_light
                brightness: 80%
                red: 100%
                green: 0
                blue: 0
            - light.turn_on:
                id: small_light
                brightness: 80%
                red: 100%
                green: 0
                blue: 0
      - if:
          condition:
            lambda: 'return id(co2_sensor).state < 700;'
          then:
            - light.turn_off: big_light
            - light.turn_off: small_light

web_server:
  port: 80

api:
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: mhz19_sensor